language: python
python:
- 2.7
before_install:
- sudo apt-get -qq update
install:
- pip install requests 
script:
- python rokugtk.py
after_success:
- openssl aes-256-cbc -K $encrypted_f57a449afedc_key -iv $encrypted_f57a449afedc_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
- openssl aes-256-cbc -K $encrypted_e4ae108ef105_key -iv $encrypted_e4ae108ef105_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
sudo: required
services:
- docker
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "apt update -qq && apt
    install snapcraft -y && cd $(pwd) && snapcraft && snapcraft push *.snap --release
    edge"
  skip_cleanup: true
